os:
  - linux
  - osx
  - windows

language: cpp

sudo: false
dist: trusty
osx_image: xcode7

addons:
  apt:
    packages:
    - xorg-dev
    - libglu1-mesa-dev
    - mesa-common-dev
    - mesa-utils-extra
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libglapi-mesa
    - libxi-dev
    - libxinerama-dev
    - libxcursor-dev
    - libxrandr-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      pip install --user cpp-coveralls;
    fi

install:

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then set -e;
    fi
  - echo "Building the library...";
  - mkdir build && cd build;
  - cmake .. -DBUILD_SHARED_LIBS=true -DBUILD_COVERAGE=true;
  - cmake --build .;
  - echo "Running Unit-Tests...";
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cp ./Debug/fractal.dll ./test/Debug/;
      ./test/Debug/unit-tests.exe;
    else ./test/unit-tests;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 
      cmake .. -DBUILD_SHARED_LIBS=false;
      cmake --build . --config Release;
    fi
  - cd ..;
  - gcov src/fractal.cpp --object-directory=./build/CMakeFiles/fractal.dir/src/;
  
after_success:		
   - coveralls --exclude tools --exclude test --exclude build --gcov-options '\-lp';
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cd build;
      cmake .. -DCMAKE_INSTALL_PREFIX=/usr .. -DBUILD_COVERAGE=false -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=false -DCPACK_GENERATOR="DEB;TGZ";
      cpack .;
    fi

deploy:
  provider: releases
  api-key:
    secure: T81rFcgrMEKUhMMxpH3Z1JKjgczYkKdfuk1nKP0XHhcpFHD5yVx3zD0tElEgDniwOVG3UuKivXDg57XynnRqCfuM5F9KIRYrjFYR3unL1LRibj9Q7EeONFOedsvT9cihlD5X4xalDOZpjGGLqeW3HgyBsC5WuXlvy7DLJeGKl7XJuFuCeYKC9yysuwvZvjcTMnGBqMPkdDGxvvIZIEJojHoJ6iXEME1146lBB7A5ZxOF/rTH2Ck7qVGWL2C/9OJ2L1kWJGQCLdRpguGvLND5ljLxKjAvoMMiuMmQouQ1aLgEtXx2G1cWVpkqVv8bfBINb1RNcGUt8twis0y5LBcBpptmaxQrotHm9LiR3EvWjaDdShCx7TCcucfMKjrmw6WZdLWKsNe2XUPW8qBGJ3GYQz5HG0W0y8Pmqsh89cF/ewXBF5Ubv8YtuKUVlC1RbmZve9bSmcLIUodJUeLo3ES12De7UjKEASA0E9fPZGzCVJbHNgb+4OpupYMrFZ8GfziVAWmm9hozxyP1raOaC2klABEek8msGaf7afsSysk+ISot56FqUhslNQGpp52yzVMUDA6KL/CR8/tDUeSETiJyhDlck9aGfdx8J7NPgPnLesCvM6hnjq4mqNDDxLBxG4vQQNVa9Vv9aah52cMgXauuOX5rxew3tXPfXiY35X7lr/4=
  file_glob: true
  file: 
    - ./fractal_*.deb
    - ./fractal_*.tar.gz
    - ./tools/Release/fractal-ui.exe
  skip_cleanup: true
  on:
    tags: true
